#Name of C compiler
CCMPL = icc
#Name of Fortran compiler
F77 = ifort
#compiling object file flags
OPT1 = -O3 -fast -parallel -ipo -no-prec-div
OPT2 = 
FFLAGS = -c  $(OPT1)
#FFLAGS = -c -O0 -g -CB
#linking flags
LFLAGS = $(OPT1)
#LFLAGS = -O0 -g -CB
#other linking flags
LFLAGS2 = -O2
#testing flags
#LFLAGS = -O0 -g -CB 
#fitsio libraries
FITSIODIR = /usr/local/lib
#Pgplot plot libraries
PGPLOTDIR = /usr/local/lib
#X11 libraries
X11DIR = /usr/X11R6/lib
# libraries for linking PGPLOT
LIBS = -L$(PGPLOTDIR) -L$(X11DIR) -lX11 -lpgplot -lpng
# libraries for linking CFITSIO
LIBS2 = -L$(PGPLOTDIR) -L$(X11DIR) -L$(FITSIODIR) -lX11 -lpgplot -lcfitsio -lpng
#Directory where executable are placed
BIN = /Users/rowe/Documents/bin/
#utils source directory
UTILS = utils/

#Listing of programs to create.

all: mostfit4 mostfit3 allMOST mostper orbitremove autocut winsigclip

autocut: mostfit3/autocut.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/autocut.f $(LIBS)

mostfit4: mostfit3/mostfit4.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/mostfit4.f $(LIBS)

jup_propmotion: Jupiter/jup_propmotion.f
	$(F77) $(LFLAGS) -o /home/rowe/p555/Jupiter/$@ \
	Jupiter/jup_propmotion.f

chris_test: mostfit3/chris_test.f90
	$(F77) $(LFLAGS) -o /home/rowe/MOST/chris/$@ \
	mostfit3/chris_test.f90 $(LIBS)

hd189733_ag: hd189733/hd189733_ag.f
	$(F77) $(LFLAGS) -o /home/rowe/MOST/hd189733_2007/package/$@ \
	hd189733/hd189733_ag.f $(LIBS)

hr1613plots: v471tau/hr1613plots.f
	$(F77) $(LFLAGS) -o /home/rowe/MOST/059_HR1613/$@ \
	v471tau/hr1613plots.f $(LIBS)

ctalkdisp: hd209458/ctalkdisp.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/ctalkdisp.f $(LIBS)

transitremove: hd209458/transitremove.f transitutil.o
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/transitremove.f transitutil.o

agmost: hd209458/agmost.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/agmost.f $(LIBS)

tempalbedo: hd209458/tempalbedo.f
	$(F77) $(LFLAGS) -o /home/rowe/bin/$@ \
	hd209458/tempalbedo.f $(LIBS)

transmission: hd209458/transmission.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458spec/$@ \
	hd209458/transmission.f $(LIBS)

mosthjd: mostper/mosthjd.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/mosthjd.f

85pegspec: 85Peg/85pegspec.f
	$(F77) $(LFLAGS) -o /home/rowe/models/zams706275/spec/85Peg/$@ \
	85Peg/85pegspec.f

gj436: hd209458/gj436.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/gj436.f $(LIBS)
	
vsini: hd189733/vsini.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ hd189733/vsini.f dataio.o $(LIBS)

transitplot: hd189733/transitplot.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ hd189733/transitplot.f dataio.o $(LIBS)

transitr8: hd209458/transitr8.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/transitr8.f $(LIBS)

transitfitnoab: hd209458/transitfitnoab.f
	$(F77) $(LFLAGS)  -o /home/rowe/hd209458comp/$@ \
	hd209458/transitfitnoab.f $(LIBS)

transitfit: hd209458/transitfit.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/transitfit.f $(LIBS)

hd209458final: hd209458/hd209458final.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ \
	hd209458/hd209458final.f dataio.o mathroutines.o nr.o
 
hjdcalc: mostper/hjdcalc.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/hjdcalc.f dataio.o

dutycycle: mostper/dutycycle.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/dutycycle.f dataio.o
	
boothist: mostper/boothist.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/boothist.f $(LIBS)

cosboot: mostper/cosboot.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/cosboot.f

sharm: aqleo/sharm.f
	$(F77) $(LFLAGS) -o $(BIN)$@ aqleo/sharm.f $(LIBS)
	
widthfix: mostfit3/widthfix.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/widthfix.f dataio.o \
	mathroutines.o nr.o

winsigclip: mostfit3/winsigclip.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/winsigclip.f dataio.o \
	mathroutines.o nr.o
	
v471add: v471tau/v471add.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ v471tau/v471add.f dataio.o

plotbins: mostfit3/plotbins.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/plotbins.f $(LIBS)

errorcheck: mostfit3/errorcheck.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/errorcheck.f \
	dataio.o $(LIBS)

limbdarkpars: hd209458/limbdarkpars.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458spec/$@ \
	hd209458/limbdarkpars.f

doublecosfit: hd209458/doublecosfit.f
	$(F77) $(LFLAGS) -o /home/rowe/hd209458comp/$@ hd209458/doublecosfit.f $(LIBS)

tidemodel: hd209458/tidemodel.f 
	$(F77) $(LFLAGS) -o /home/rowe/bin/$@ hd209458/tidemodel.f \
	$(LIBS)
	
freqremove: mostfit3/freqremove.f dataio.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/freqremove.f \
	dataio.o

crosstalk: mostfit3/crosstalk.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/crosstalk.f \
	dataio.o mathroutines.o nr.o $(LIBS)

csvcor: hd209458/csvcor.f
	$(F77) $(LFLAGS) -o $(BIN)$@ hd209458/csvcor.f

avgskyfit: mostfit3/avgskyfit.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/avgskyfit.f \
	dataio.o mathroutines.o nr.o

v471_fit: mostfit3/v471_fit.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o /home/rowe/MOST/V471Tau/$@ mostfit3/v471_fit.f \
	dataio.o mathroutines.o nr.o

plotphase: hd209458/plotphase.f dataio.o mathroutines.o \
	timedomain.o nr.o graphics.o fit.o
	$(F77) $(LFLAGS) -o $(BIN)$@ hd209458/plotphase.f dataio.o \
	mathroutines.o timedomain.o nr.o graphics.o fit.o $(LIBS)
	
phasedata: hd209458/phasedata.f
	$(F77) $(LFLAGS) -o $(BIN)$@ hd209458/phasedata.f

orbitremove: mostfit3/orbitremove.f dataio.o mathroutines.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/orbitremove.f dataio.o \
	mathroutines.o nr.o

bayes: hd209458/bayes.f lcurvefit.o
	$(F77) $(LFLAGS) -warn -o /home/rowe/hd209458comp/bayes \
	hd209458/bayes.f lcurvefit.o $(LIBS)

flatMOST: allMOST/flatMOST.f
	$(F77) $(LFLAGS) -o /home/rowe/MOST/flatMOST allMOST/flatMOST.f \
	$(LIBS)

flatstat: flatstat/flatstat.f nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ flatstat/flatstat.f nr.o

comparecurve: mostfit3/comparecurve.f graphics.o dataio.o mathroutines.o \
	timedomain.o nr.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/comparecurve.f dataio.o \
	graphics.o mathroutines.o timedomain.o nr.o $(LIBS)

dataconvert: $(UTILS)/dataconvert.f
	$(F77) $(LFLAGS) -o $(BIN)$@ $(UTILS)dataconvert.f

mostper: mostper/mostper.f
	$(F77) $(LFLAGS) -o $(BIN)$@ mostper/mostper.f $(LIBS)

mostfit3: mostfit3/mostfit3.f dataio.o timedomain.o \
	mathroutines.o nr.o skyremove.o graphics.o magpixel.o
	$(F77) $(LFLAGS) -o $(BIN)$@ mostfit3/mostfit3.f dataio.o \
	timedomain.o mathroutines.o nr.o skyremove.o graphics.o \
	magpixel.o $(LIBS)

allMOST: allMOST/allmost.f fitsreader.o fitsdataio.o fabphot.o findpeaks2.o
	$(F77) $(LFLAGS) -o $(BIN)allMOST allMOST/allmost.f \
	fitsreader.o fitsdataio.o fabphot.o findpeaks2.o $(LIBS2)

hd209458comp: hd209458/hd209458comp.f mathroutines.o \
	timedomain.o nr.o graphics.o fit.o dataio.o lcurvefit.o
	$(F77) $(LFLAGS) -o $(BIN)$@ hd209458/$@.f mathroutines.o \
	timedomain.o nr.o graphics.o fit.o dataio.o lcurvefit.o $(LIBS) 

#building object libraries

mathroutines.o: $(UTILS)mathroutines.f
	$(F77) $(FFLAGS) $(UTILS)mathroutines.f
timedomain.o: $(UTILS)timedomain.f
	$(F77) $(FFLAGS) $(UTILS)timedomain.f
nr.o: $(UTILS)nr.f
	$(F77) $(FFLAGS) $(UTILS)nr.f
graphics.o: $(UTILS)graphics.f
	$(F77) $(FFLAGS) $(UTILS)graphics.f
fit.o: $(UTILS)fit.f
	$(F77) $(FFLAGS) $(UTILS)fit.f
dataio.o: $(UTILS)dataio.f
	$(F77) $(FFLAGS) $(UTILS)dataio.f
skyremove.o: $(UTILS)skyremove.f
	$(F77) $(FFLAGS) $(UTILS)skyremove.f
fitsdataio.o: $(UTILS)fitsdataio.f
	$(F77) $(FFLAGS) $(UTILS)fitsdataio.f
fitsreader.o: allMOST/fitsreader.f
	$(F77) $(FFLAGS) allMOST/fitsreader.f
magpixel.o:	$(UTILS)magpixel.f
	$(F77) $(FFLAGS) $(UTILS)magpixel.f
fabphot.o: allMOST/fabphot.f
	$(F77) $(FFLAGS) allMOST/fabphot.f
lcurvefit.o: hd209458/lcurvefit.f
	$(F77) $(FFLAGS) hd209458/lcurvefit.f
transitutil.o: $(UTILS)transitutil.f
	$(F77) $(FFLAGS) $(UTILS)transitutil.f
findpeaks2.o: allMOST/findpeaks2.f
	$(F77) $(FFLAGS) allMOST/findpeaks2.f

# Removing object files
.PHONY : clean
clean :
	rm *.o
